"""Cross-package sign -> verify contract for a guardian stop RELEASE (K8, crypto.md S2.3). The guardian's
real builder (`stop_release.build_release_events`) signs a fixed Tier-2 release with a fixed TEST-ONLY
seed; the result is pinned in `interfaces/fixtures/signed_stop_release.json`, which the hub simulator
verifies and applies with its own code (`integration-sims/tests/test_signed_stop_release_fixture.py`).
Regenerate after an intended change with:

    PYTHONPATH=src python -m tests.unit.guardian.test_signed_stop_release_fixture
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from uuid import UUID

from opengrid.core.crypto import private_key_from_seed
from opengrid.guardian import stop_release
from opengrid.guardian.ports import EngagedStop, ReleaseRequest

FIXTURE = Path(__file__).resolve().parents[4] / "interfaces" / "fixtures" / "signed_stop_release.json"

# TEST-ONLY key material: the same fixed, public, non-secret seed as signed_command_batch.json.
_TEST_SEED = bytes(range(32))
_ISSUED_AT = datetime(2026, 9, 26, 18, 30, 0, 250000, tzinfo=UTC)


def build_fixture() -> dict[str, Any]:
    request = ReleaseRequest(
        operator_action_id=UUID("00000000-0000-4000-8000-0000000000a1"),
        requested_by="operator:alice",
        approved_by="operator:bob",
        scope_kind="BANK",
        scope_ref="bank-000",
        reason="feeder repaired, stop reason cleared",
        requested_at=_ISSUED_AT - timedelta(minutes=2),
        approved_at=_ISSUED_AT - timedelta(minutes=1),
        trace_id=UUID("00000000-0000-4000-8000-0000000000a2"),
    )
    engaged = [
        EngagedStop(
            stop_id=UUID("00000000-0000-4000-8000-0000000000e1"),
            initiator_kind="SAFESTOP_AUTHORITY",
            engaged_at=_ISSUED_AT - timedelta(hours=1),
        )
    ]
    (event,) = stop_release.build_release_events(
        request, engaged, seed=_TEST_SEED, key_id="guardian-test", issued_at=_ISSUED_AT
    )
    return {
        "_comment": "TEST-ONLY. Generated by orchestrator/tests/unit/guardian/test_signed_stop_release_fixture.py.",
        "guardian_public_key_hex": private_key_from_seed(_TEST_SEED).public_key().public_bytes_raw().hex(),
        "release": json.loads(event.model_dump_json()),
    }


def test_fixture_matches_what_the_guardian_signs_today():
    assert FIXTURE.exists(), f"missing {FIXTURE}; regenerate it (see module docstring)"
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == build_fixture()


if __name__ == "__main__":
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {FIXTURE}")
