"""Cross-package sign -> verify contract for calibration commands (S6.7, crypto.md S2.1 pattern). The
orchestrator side signs a fixed command through the guardian's REAL signing path
(`GuardianService.evaluate_and_sign_calibration`, G-20/G-25 passing) with a fixed TEST-ONLY seed and
pins the result in `interfaces/fixtures/signed_calibration_command.json`; the `ogsim` side verifies the
same file with the hub's own `verify_calibration_signature`. If this test fails after an intended change
to the signing path, regenerate the fixture with:

    PYTHONPATH=src python -m tests.unit.guardian.test_signed_calibration_fixture
"""

from __future__ import annotations

import asyncio
import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from uuid import UUID

from opengrid.core.crypto import private_key_from_seed, verify_payload
from opengrid.core.models.pq import CalibrationReference
from opengrid.core.pq import DEFAULT_FIRMWARE_CALIBRATION_BOUNDS, CalibrationBounds, OffsetVector
from opengrid.guardian.config import GuardianConfig
from opengrid.guardian.ports import GuardianPorts, PqPorts
from opengrid.guardian.pq_ports import ProposedCalibrationCommand
from opengrid.guardian.service import GuardianService

FIXTURE = Path(__file__).resolve().parents[4] / "interfaces" / "fixtures" / "signed_calibration_command.json"

# TEST-ONLY key material: the same fixed, public, non-secret seed as signed_command_batch.json.
_TEST_SEED = bytes(range(32))
_ISSUED_AT = datetime(2026, 9, 26, 18, 0, 2, 104000, tzinfo=UTC)


class _FixtureWorld:
    """Every port the calibration path reads, answering "safe to calibrate" (and a perfect clock)."""

    async def offset_from_ntp_ms(self) -> float:
        return 0.0

    async def append_calibration_verdict(self, calibration_id: UUID, payload: dict[str, object]) -> None:
        return None

    async def append_stop_release_verdict(self, operator_action_id: UUID, payload: dict[str, object]) -> None:
        return None

    async def max_bounds_for_hub(self, hub_id: str) -> CalibrationBounds:
        return DEFAULT_FIRMWARE_CALIBRATION_BOUNDS

    async def last_attempt_epoch_s(self, hub_id: str) -> float | None:
        return None

    async def has_active_non_default_envelope_grant(self, hub_id: str) -> bool:
        return False


def _signed_command() -> dict[str, Any]:
    world = _FixtureWorld()
    pq = PqPorts(world, world, world, world, world, world)  # type: ignore[arg-type]
    ports = GuardianPorts(world, None, world, None, None, None, None, None, None, None, None, pq=pq)  # type: ignore[arg-type]
    service = GuardianService(
        ports=ports,
        config=GuardianConfig(key_path="", key_id="guardian-test"),
        signing_seed=_TEST_SEED,
        now_fn=lambda: _ISSUED_AT,
    )
    proposed = ProposedCalibrationCommand(
        hub_id="hub-00001",
        correction=OffsetVector(freq_hz=-0.02, voltage_pct=0.4, phase_deg=1.25),
        bounds=DEFAULT_FIRMWARE_CALIBRATION_BOUNDS,
        calibration_id=UUID("00000000-0000-4000-8000-0000000000c1"),
        reference=CalibrationReference(
            phase_deg=0.0, freq_hz=60.0, amplitude_v=240.0, sync_source="ntp_disciplined"
        ),
        issued_at=_ISSUED_AT,
        expires_at=_ISSUED_AT + timedelta(seconds=60),
    )
    command = asyncio.run(service.evaluate_and_sign_calibration(proposed))
    assert command is not None
    result: dict[str, Any] = json.loads(command.model_dump_json())
    return result


def build_fixture() -> dict[str, Any]:
    public_hex = private_key_from_seed(_TEST_SEED).public_key().public_bytes_raw().hex()
    return {
        "_comment": "TEST-ONLY. Generated by orchestrator/tests/unit/guardian/test_signed_calibration_fixture.py.",
        "guardian_public_key_hex": public_hex,
        "command": _signed_command(),
    }


def test_fixture_matches_what_the_guardian_signs_today():
    assert FIXTURE.exists(), f"missing {FIXTURE}; regenerate it (see module docstring)"
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == build_fixture()


def test_fixture_signature_covers_every_field_but_key_id_and_signature():
    data = build_fixture()
    command = data["command"]
    signed = {k: v for k, v in command.items() if k not in ("key_id", "signature")}
    public = bytes.fromhex(data["guardian_public_key_hex"])
    assert verify_payload(public, signed, command["signature"])
    assert not verify_payload(public, {**signed, "hub_id": "hub-00002"}, command["signature"])


if __name__ == "__main__":
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {FIXTURE}")
