"""Cross-package sign -> verify contract (crypto.md S2.1). `opengrid` and `ogsim` cannot import each
other, so the orchestrator side signs a fixed batch with a fixed TEST-ONLY seed and pins the result in
`interfaces/fixtures/signed_command_batch.json`; `integration-sims/tests/test_signed_batch_fixture.py`
verifies that same file with the hub's own code. If this test fails after an intended change to the
signing path, regenerate the fixture with:

    PYTHONPATH=src python -m tests.unit.guardian.test_signed_batch_fixture
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import UUID

from opengrid.core.crypto import generate_keypair, private_key_from_seed
from opengrid.guardian import main as guardian_main
from opengrid.guardian.ports import ProposedBatch, ProposedItem
from opengrid.guardian.service import GuardianService

FIXTURE = Path(__file__).resolve().parents[4] / "interfaces" / "fixtures" / "signed_command_batch.json"

# TEST-ONLY key material: a fixed, public, non-secret seed so the signature is reproducible.
_TEST_SEED = bytes(range(32))
_ISSUED_AT = datetime(2026, 9, 26, 18, 0, 2, 104000, tzinfo=UTC)


def build_fixture() -> dict:
    proposal = ProposedBatch(
        command_batch_id=UUID("00000000-0000-4000-8000-000000000001"),
        bank_id="bank-000",
        cycle_id="fixture",
        epoch=3,
        seq=17,
        issued_at=_ISSUED_AT,
        expires_at=_ISSUED_AT + timedelta(seconds=10),
        ledger_version=1,
        items=[
            ProposedItem(hub_id="hub-00001", p_kw_setpoint=-3.2, reason_code="SELECTOR"),
            ProposedItem(hub_id="hub-00002", p_kw_setpoint=11.0, reason_code="SELECTOR"),
        ],
    )
    service = GuardianService(ports=None, config=None, signing_seed=_TEST_SEED)  # type: ignore[arg-type]
    batch = guardian_main.build_signed_batch(service, key_id="guardian-test", proposal=proposal)
    public_hex = private_key_from_seed(_TEST_SEED).public_key().public_bytes_raw().hex()
    return {
        "_comment": "TEST-ONLY. Generated by orchestrator/tests/unit/guardian/test_signed_batch_fixture.py.",
        "guardian_public_key_hex": public_hex,
        "batch": json.loads(batch.model_dump_json()),
    }


def test_fixture_matches_what_the_guardian_signs_today():
    assert FIXTURE.exists(), f"missing {FIXTURE}; regenerate it (see module docstring)"
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == build_fixture()


def test_fixture_seed_is_not_a_generated_key():
    seed, _public = generate_keypair()
    assert seed != _TEST_SEED


if __name__ == "__main__":
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {FIXTURE}")
