#!/usr/bin/env python3
"""deploy/scripts/gen_sim_overrides.py -- generate the production sim configs with the approved zone blocks on.

The repo's `integration-sims/config/{fleet,scada}.yaml` declare every zone block but ship them disabled (tests
pin that). Production enables the blocks the owner approved (LZ_AEN since 2026-09-26; LZ_LCRA/LZ_RAYBN when enabled --
regulated and UNAVAILABLE per D-37) through generated copies in `/etc/opengrid/sim/`, which `og-sim-fleet`/`og-sim-scada` load through
drop-ins and which `opengrid.fleet.seed` / `dev/seed/topology_seed.py` read to seed the same hubs and banks.
This is the repo version of the release manager's `aen.sh pre` step, generalised to a list of zones.

    python deploy/scripts/gen_sim_overrides.py --release <release_dir> --out /etc/opengrid/sim --zones LZ_AEN
    python deploy/scripts/gen_sim_overrides.py ... --dry-run     # print what would change, write nothing

Every other key is copied unchanged. A zone that is not declared in both files is an error (a typo must never
silently seed a different fleet). Output is deterministic, so re-running is a no-op.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

FILES = ("fleet", "scada")


def render(src: Path, zones: set[str]) -> tuple[str, list[str]]:
    cfg: dict[str, Any] = yaml.safe_load(src.read_text(encoding="utf-8")) or {}
    blocks = cfg.get("zone_blocks") or []
    declared = {str(b.get("zone")) for b in blocks if isinstance(b, dict)}
    missing = sorted(zones - declared)
    if missing:
        raise SystemExit(f"{src}: zone block(s) not declared: {', '.join(missing)}")
    enabled = []
    for block in blocks:
        if isinstance(block, dict):
            block["enabled"] = str(block.get("zone")) in zones
            if block["enabled"]:
                enabled.append(str(block["zone"]))
    header = (
        f"# GENERATED by deploy/scripts/gen_sim_overrides.py from the release's {src.name}; enabled zone blocks: "
        f"{', '.join(enabled) or 'none'}. Regenerate on every release that changes that file.\n"
    )
    return header + yaml.safe_dump(cfg, sort_keys=False), enabled


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--release", type=Path, required=True, help="release/repo root holding integration-sims/")
    p.add_argument("--out", type=Path, required=True, help="output directory, e.g. /etc/opengrid/sim")
    p.add_argument("--zones", default="LZ_AEN", help="comma-separated zone blocks to enable ('' for none)")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    zones = {z.strip() for z in args.zones.split(",") if z.strip()}
    for name in FILES:
        src = args.release / "integration-sims" / "config" / f"{name}.yaml"
        dst = args.out / f"{name}.yaml"
        text, enabled = render(src, zones)
        current = dst.read_text(encoding="utf-8") if dst.exists() else None
        state = "unchanged" if current == text else ("would write" if args.dry_run else "written")
        if not args.dry_run and current != text:
            args.out.mkdir(parents=True, exist_ok=True)
            dst.write_text(text, encoding="utf-8")
        print(f"{dst}: {state} (enabled: {', '.join(enabled) or 'none'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
