#!/usr/bin/env python3
"""Generate dev/mosquitto/opengrid.acl from the same per-user topic grants as production's
/etc/mosquitto/opengrid.acl (read read-only over ssh from 192.168.5.35 on 2026-09-25, per
BUILD.md's "the Mosquitto ACL model" instruction -- see the structure comparison in
dev/README.md's Verification section).

The six users and grants below are a **direct transcription** of production's ACL, with only
the topic root made a parameter (production is `og/v1`; the dev stack also defaults to `og/v1`
since it is single-tenant and needs no `ogtest/<workspace>` scoping -- see
`tools/remote.ps1`/BUILD.md S5 for why production/server-testing needs that scoping and the dev
stack does not).

Run via `make -C dev dev-up` (it is invoked automatically) or directly:
    python dev/scripts/gen_mosquitto_acl.py [--topic-root og/v1] [--out dev/mosquitto/opengrid.acl]

The username list is cross-checked against dev/secrets(.example) -- every `OG_MQTT_*_PASSWORD`
key there must have a matching grant block below, and vice versa, so the ACL, the password file
(dev/scripts/gen-mosquitto-passwd.sh) and the actual MQTT clients (opengrid.platform.mqtt,
ogsim.common.config, ogsim.control.mqtt_pub) never silently drift apart.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEV_DIR = Path(__file__).resolve().parents[1]

# (username, [(access, topic_suffix), ...]) -- topic_suffix is joined onto "<topic_root>/".
# Order and content match production's /etc/mosquitto/opengrid.acl exactly (BUILD.md: "an ACL
# equivalent to production").
_USER_GRANTS: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "og_sim",
        [
            ("write", "tel/#"),
            ("write", "ack/#"),
            ("read", "cmd/#"),
            ("read", "stop/#"),
            ("read", "lease/#"),
            ("write", "scada/#"),
            ("read", "scada/ctl/#"),
            ("readwrite", "scenario/#"),
        ],
    ),
    (
        "og_simctl",
        [
            ("readwrite", "scenario/#"),
            ("write", "scada/#"),
            ("read", "#"),
        ],
    ),
    (
        "og_engine",
        [
            ("read", "tel/#"),
            ("read", "ack/#"),
            ("read", "scada/#"),
            ("read", "stop/#"),
        ],
    ),
    (
        "og_guardian",
        [
            ("write", "cmd/#"),
            ("write", "lease/#"),
            ("read", "ack/#"),
            ("read", "tel/#"),
        ],
    ),
    (
        "og_safestop",
        [
            ("write", "stop/#"),
            ("read", "ack/#"),
        ],
    ),
    (
        "og_api",
        [
            ("read", "#"),
        ],
    ),
]

_SECRET_KEY_RE = re.compile(r"^OG_MQTT_([A-Z0-9]+)_PASSWORD=")


def _usernames_from_grants() -> set[str]:
    return {user for user, _ in _USER_GRANTS}


def _usernames_from_secrets_file(path: Path) -> set[str]:
    """Parses dev/secrets(.example)'s `OG_MQTT_<NAME>_PASSWORD=...` lines into lowercased
    `og_<name>` usernames, e.g. `OG_MQTT_SIMCTL_PASSWORD` -> `og_simctl`."""
    if not path.exists():
        return set()
    names = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _SECRET_KEY_RE.match(line.strip())
        if match:
            names.add(f"og_{match.group(1).lower()}")
    return names


def render_acl(topic_root: str) -> str:
    lines = [
        f"# GENERATED by dev/scripts/gen_mosquitto_acl.py -- do not edit by hand.",
        f"# Mirrors production /etc/mosquitto/opengrid.acl (topic root {topic_root!r}).",
        "",
    ]
    for user, grants in _USER_GRANTS:
        lines.append(f"user {user}")
        for access, suffix in grants:
            lines.append(f"topic {access} {topic_root}/{suffix}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--topic-root", default="og/v1")
    parser.add_argument("--out", default=str(DEV_DIR / "mosquitto" / "opengrid.acl"))
    parser.add_argument(
        "--secrets-file",
        default=None,
        help="defaults to dev/secrets if present, else dev/secrets.example",
    )
    args = parser.parse_args(argv)

    secrets_path = (
        Path(args.secrets_file)
        if args.secrets_file
        else (DEV_DIR / "secrets" if (DEV_DIR / "secrets").exists() else DEV_DIR / "secrets.example")
    )
    secrets_users = _usernames_from_secrets_file(secrets_path)
    grant_users = _usernames_from_grants()
    if secrets_users and secrets_users != grant_users:
        missing_in_secrets = grant_users - secrets_users
        missing_in_grants = secrets_users - grant_users
        print(
            "gen_mosquitto_acl: user list mismatch between this script and "
            f"{secrets_path} -- in ACL but not secrets: {sorted(missing_in_secrets)}; "
            f"in secrets but not ACL: {sorted(missing_in_grants)}",
            file=sys.stderr,
        )
        return 1

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_acl(args.topic_root), encoding="utf-8")
    print(f"wrote {out_path} ({len(_USER_GRANTS)} users, topic root {args.topic_root!r})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
