"""Regenerates `openapi.json` and `reference.md` from the real FastAPI app (no DB, no MQTT needed).

Run from the repository root with the orchestrator installed:  python docs/api/generate_reference.py
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.dependencies.models import Dependant
from fastapi.routing import APIRoute

from opengrid.api import create_app
from opengrid.api.auth import require_loopback_health_probe, require_operator, require_viewer

OUTPUT_DIR = Path(__file__).resolve().parent
API_PREFIX = "/og/api/"
ROLE_BY_GUARD = {
    require_operator: "operator",
    require_viewer: "viewer",
    require_loopback_health_probe: "loopback only",
}


def _walk(dependant: Dependant) -> Iterator[Dependant]:
    yield dependant
    for child in dependant.dependencies:
        yield from _walk(child)


def _role_for(route: APIRoute) -> str:
    roles = {ROLE_BY_GUARD[d.call] for d in _walk(route.dependant) if d.call in ROLE_BY_GUARD}
    for role in ("operator", "loopback only", "viewer"):
        if role in roles:
            return role
    return "viewer"


def _api_routes(routes: list[Any]) -> Iterator[APIRoute]:
    for route in routes:
        if isinstance(route, APIRoute):
            yield route
        elif hasattr(route, "original_router"):
            yield from _api_routes(route.original_router.routes)


def _roles_by_operation(app: FastAPI) -> dict[tuple[str, str], str]:
    return {(method, route.path): _role_for(route) for route in _api_routes(app.routes) for method in route.methods}


def _type_of(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_type_of(option) for option in schema["anyOf"])
    if schema.get("type") == "array":
        return f"array of {_type_of(schema.get('items', {}))}"
    return str(schema.get("type", "any"))


def _body_fields(operation: dict[str, Any], components: dict[str, Any]) -> list[str]:
    content = operation.get("requestBody", {}).get("content", {})
    schema = next(iter(content.values()), {}).get("schema")
    if not schema:
        return []
    model = components.get(_type_of(schema), schema)
    required = set(model.get("required", []))
    return [
        f"`{name}` ({_type_of(prop)}{', required' if name in required else ''})"
        for name, prop in model.get("properties", {}).items()
    ]


def _parameters(operation: dict[str, Any]) -> list[str]:
    return [
        f"`{p['name']}` ({p['in']}, {_type_of(p.get('schema', {}))}{', required' if p.get('required') else ''})"
        for p in operation.get("parameters", [])
    ]


def _render_operation(method: str, path: str, operation: dict[str, Any], role: str, components: dict) -> list[str]:
    lines = [f"### `{method} {path}`", "", f"{operation.get('summary', '')}. Role: **{role}**.", ""]
    if description := operation.get("description"):
        lines += [description.strip(), ""]
    for label, items in (("Parameters", _parameters(operation)), ("Body", _body_fields(operation, components))):
        if items:
            lines += [f"{label}: " + "; ".join(items), ""]
    lines += ["Responses: " + ", ".join(f"`{code}`" for code in operation["responses"]), ""]
    return lines


def _group_of(path: str) -> str:
    return path.removeprefix(API_PREFIX).split("/", 1)[0]


def render_reference(spec: dict[str, Any], roles: dict[tuple[str, str], str]) -> str:
    components = spec.get("components", {}).get("schemas", {})
    operations = sorted(
        (_group_of(path), path, method.upper(), operation)
        for path, item in spec["paths"].items()
        if path.startswith(API_PREFIX)
        for method, operation in item.items()
    )
    lines = ["# REST API reference", "", "Generated by `generate_reference.py` from the FastAPI app; do not edit.", ""]
    current_group = None
    for group, path, method, operation in operations:
        if group != current_group:
            lines += [f"## {group}", ""]
            current_group = group
        lines += _render_operation(method, path, operation, roles.get((method, path), "viewer"), components)
    return "\n".join(lines)


def main() -> None:
    app = create_app()
    spec = app.openapi()
    (OUTPUT_DIR / "openapi.json").write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (OUTPUT_DIR / "reference.md").write_text(render_reference(spec, _roles_by_operation(app)), encoding="utf-8")


if __name__ == "__main__":
    main()
